### ISSUE TITLE
"arrayStats" package?

### ISSUE THREAD

**Issue by mayer79** [HenrikBengtsson/matrixStats#102]
The functions in `matrixStats` are extremely useful.  Are there plans for an equivalent `arrayStats` package in order to calculate important stats over axes? 

Example
```
set.seed(3345)
ind <- sample(c(FALSE, TRUE), 24, replace = TRUE)
x <- array(ind, dim = c(2, 3, 4))

apply(x, 1:2, any)
arrayAnys(x, axis = 1:2)
```

**Comment by HenrikBengtsson** [comment]
Hi, thanks for reaching out.  

This is a wish that comes up once is a while and I/we also considered this alternative before starting the project.  However, the problem domain of working with arrays is much larger than sticking with matrices and in order to limit the aims and to deliver, I decided to go with functions operating on matrices (and some functions operating on vectors).  This also makes it easier to further optimize the performance of the code.

I don't have any plans of making an `arrayStats` package that generalize the `matrixStats` ideas from matrices to arrays of any dimensions.  The main reason is that it's a rather big task and I simply don't have the capacity / resources to do that.

**Comment by mayer79** [comment]
Good point. Maybe at some point you are so bored with other stuff that you can start on this ;)
