### ISSUE TITLE
Large Matrix Crashing R on Windows

### ISSUE THREAD

**Issue by bstewart** [HenrikBengtsson/matrixStats#104]
In the process of debugging an error in the stm bstewart/stm#89 , we stumbled across a windows-specific issue that causes R to crash.  I don't know what feature causes the problem, but you can reliably generate the problem using `rowLogSumExps` on a very large matrix.  

```
library("matrixStats")
x <- matrix(runif(1e5*70), nrow=1e5)
y <- rowLogSumExps(x) # this causes the crash
```

This is using the latest version of R 3.4.1 and the cran version of matrixStats 0.52.2 on a Windows machine (64 bit).  We have resolved the issue in stm so no rush on our part- I just thought you might want to be aware as I myself rarely do tests more complicated than CRAN checks on Windows and thus miss these kinds of things.

Thanks so much for the amazing package- I've used it for years and greatly enjoyed it.

**Comment by HenrikBengtsson** [comment]
Thanks for the kind words and thanks for reporting.  Just for my / others troubleshooting, does it crash every single time with that code or once in a while?  Do you know if it crashes also when running via good old Rterm?   Also, do you have some specs on the Windows machine, e.g. RAM and Windows version?

**Comment by bstewart** [comment]
Sure! I'm going to mention @adeldaoud who can share specs on the machines he found the bug on (he verified with several.

- It does crash every single time with that code (on the Windows machines we have tried)
- I've tried R's native GUI and RStudio and both cause crashes.  I have not tried running from command line (because honestly I can't remember how on Windows!),
- the test machine I found is running Windows 10 Home with 12 GB of RAM.  I can do `log(rowSums(exp(x)))` without any problems though so I really doubt its a memory ceiling.

**Comment by adeldaoud** [comment]
Hi @HenrikBengtsson , I tested to run the a version of hte code @bstewart wrote and the original large matrix on two computers. The crash happens on both, and the crash is systematic. 

Specs:

* First pc:  
![image](https://user-images.githubusercontent.com/9431362/29753117-cce56612-8b6a-11e7-9cb6-af518e032470.png)

* Second pc:
![image](https://user-images.githubusercontent.com/9431362/29753126-ecb73394-8b6a-11e7-8b7b-660e491b9b19.png)

I also monitored memory and cpu usage with Windows internal tracking, and they never hits the ceiling. Implying, that neither of this are the driving mechanism behind the crash.

Hope this helps

**Comment by HenrikBengtsson** [comment]
Using a Windows 8.1 VM, I can _reproduce the crash with **64-bit R** (using Rgui.exe, R.exe / Rterm.exe, and Rscript.exe)_, including R 3.3.3 (2017-03-06), R 3.4.0 (2017-04-21), R 3.4.1 (2017-06-30), R 3.4.1 patched (2017-07-07 r72898) all installed from [CRAN binaries](https://cran.r-project.org/bin/windows/base/)).  What's interesting, and most likely a clue, is that the crash does not occur when running corresponding 32-bit R binaries.

A minimal reproducible crash example from the Windows Command line:
```sh
Rscript -e "x <- matrix(0.0, nrow = 32762, ncol = 2); y <- matrixStats::rowLogSumExps(x)"
```
whereas with 32,761 rows, it does _not_ crash.

Thanks for the reports - I'll investigate.

**Comment by HenrikBengtsson** [comment]
More updates: by adding [a package test](https://github.com/HenrikBengtsson/matrixStats/commit/d0856fd64b4d905d94f17ae6c2d77c1aba60c7a7):
```r
x <- matrix(0.0, nrow=32762, ncol=2)
y <- matrixStats::rowLogSumExps(x)
str(y)
```
I managed to reproduce it also on:

* AppVeyor CI using [64-bit R 3.4.1 (2017-06-30)](https://ci.appveyor.com/project/HenrikBengtsson/matrixstats/build/1.0.342/job/242klgj4wmkyy8o0) (but not 64-bit R-devel - not sure why).
* win-builder using [64-bit R 3.4.1 (2017-06-30) but not the 32-bit version](https://win-builder.r-project.org/M5Fkhxk1M2F7/00check.log).
* R-hub using [64-bit R 3.4.1 (2017-06-30)](https://builder.r-hub.io/status/original/matrixStats_0.52.2-9000.tar.gz-78e29f9fe6864df7a12920a210349b8c)

Since the crash can be reproduced using package tests and CI services, the test also works as a regression test.  Another advantage with these services, is that they build/installs matrixStats from source meaning we can rule out that it's a broken CRAN-specific binary of matrixStats 0.52.2.

Oddly enough, I did _not_ managed to reproduce it on R devel:

* AppVeyor CI using [64-bit R devel (2017-08-28 r73149)](https://ci.appveyor.com/project/HenrikBengtsson/matrixstats/build/job/242klgj4wmkyy8o0)
* win-builder using [64-bit R devel (2017-08-30 r73159)](https://win-builder.r-project.org/oVu6PGdKP9dm/00check.log)
* R-hub using [64-bit R devel (2017-07-29 r72997)](https://builder.r-hub.io/status/original/matrixStats_0.52.2-9000.tar.gz-ef0d184822fa4ecb9eb2251078d2498e)

---

Also, the crash also occurs with:
```sh
Rscript -e "x <- matrix(NA_real_, nrow=32762, ncol=2); y <- matrixStats::rowLogSumExps(x, na.rm = FALSE); str(y)"
```
meaning we might rule out certain pieces of the code.

**Comment by HenrikBengtsson** [comment]
@jeroen, I'm reaching out to you because I'm in the dark.  I'm running into a bug somewhere that causes one function in matrixStats to crash in a very reproducible way on Windows 64-bit R (not 32-bit) and not on R-devel, but on R 3.3.3, R 3.4.0, R 3.4.1 and R 3.4.1 patched.  I can reproduce it on various CI services.  See https://github.com/HenrikBengtsson/matrixStats/issues/104#issuecomment-325852781.  I run lots of validation on the package, including valgrind, ASan and UBSan, and they don't report anything.

Since it does _not_ crash on R-devel, which is built using your gcc 4.9.3 toolchain, do you think this could possibly have to do with broken compiler optimizations or similar inherited from the old toolchain?

**Comment by jeroen** [comment]
The compiler hasn't changed between 3.3.0 and 3.5.0 so I doubt this is the problem.

R base has fixed quite a few bugs for support of "long vectors" recently, perhaps this is be related.

**Comment by jeroen** [comment]
@HenrikBengtsson can you narrow down at which point in the C code the crash occurs? I tried to have a look at your code but I got lost in the C macro jungle.

**Comment by HenrikBengtsson** [comment]
@jeroen, are you saying that your gcc 4.9.3 toolchain is in place since R 3.3.0?  I understood it as **your toolchain is only in R-devel** since https://cloud.r-project.org/bin/windows/base/rdevel.html says:

"This build of R-Devel uses the gcc 4.9.3 toolchain produced by Jeroen Ooms. ..."

whereas neither https://cloud.r-project.org/bin/windows/base/rpatched.html nor https://cloud.r-project.org/bin/windows/base/index.html does so.

---

I wanted to consider the above before going in to the "jungle" with a Windows VM machete.  I'll head in there at some point and when I do I'll let you know what I find.  No need for you to spend any time on this.  FYI, the macro-based templates are there for maximum performance (at the cost of trickier code and larger builds).

**Comment by HenrikBengtsson** [comment]
Hey, I did my 16+ year service for R users on Windows ;)  I'll probably end up extracting a minimal core of 
the package and to trial'n'error debugging using print statements ... in a VM :/

**Comment by HenrikBengtsson** [comment]
Solved; it was a C-level bug / typo:  [Passed an `R_xlen_t` argument `by` to an internal function function as an `int`](https://github.com/HenrikBengtsson/matrixStats/commit/62a5612e17793b967d27e7714bb7274716784181#diff-64d91dd0a1b5aafb6b51e13bd332b84e).  Not sure why this was not reported as a warning / note by the compilers, and not sure why it only affected Windows (could be related to padding of data types).

Added [explicit package test for the bug](https://github.com/HenrikBengtsson/matrixStats/commit/62a5612e17793b967d27e7714bb7274716784181#diff-b59b28b32c07ff24f6238433cc15e07b).  Package now passes this test on [AppVeyor CI](https://ci.appveyor.com/project/HenrikBengtsson/matrixstats/build/1.0.346), win-builder, and R-Hub.

Thanks for reporting.

**Comment by renswilderom** [comment]
Dear Hendrik, unfortunately I run into this problem again. I'm using a 64-bit windows machine (see details in attachment). I repeatedly encountered the problem while working with the Structural Topic Model (STM) package, and when running this test:
```
library("matrixStats")
x <- matrix(runif(1e5*70), nrow=1e5)
y <- rowLogSumExps(x) # this causes the crash

```
Could I provide you with more information so you could look into the problem?

Best wishes

<img width="335" alt="system1" src="https://user-images.githubusercontent.com/27849748/32116169-8711e336-bb17-11e7-8470-ff4316b91e7a.png">
<img width="264" alt="system2" src="https://user-images.githubusercontent.com/27849748/32116170-87223222-bb17-11e7-80cc-841407d686bb.png">

,

Rens

**Comment by HenrikBengtsson** [comment]
What version of matrixStats?  Note that the version on CRAN still has the bug.

**Comment by renswilderom** [comment]
Im using version 0.52.2
Installed through:

`devtools::install_github("HenrikBengtsson/matrixStats")`

**Comment by HenrikBengtsson** [comment]
source('http://callr.org/install#HenrikBengtsson/matrixStats@develop')

cf README.md

**Comment by renswilderom** [comment]
Thanks, I installed R tools and runned from R studio:

`source('http://callr.org/install#HenrikBengtsson/matrixStats@develop')` this gives 

> Error in file(filename, "r", encoding = encoding) : 
>   cannot open the connection
> In addition: Warning message:
> In file(filename, "r", encoding = encoding) :
>   cannot open URL 'http://callr.org/install#HenrikBengtsson/matrixStats@develop': HTTP status was '400 Bad Request'

Other attempts also did not work, for example: 
`devtools::install_url("http://callr.org/install#HenrikBengtsson/matrixStats@develop")` gives

> Downloading package from url: http://callr.org/install#HenrikBengtsson/matrixStats@develop
> Installation failed: Don't know how to decompress files with extension

**Comment by renswilderom** [comment]
Hi, it appeared to be a PATH variable problem with Rtools. The answer to this Stackoverflow item helped me: https://stackoverflow.com/questions/33103203/rtools-is-not-being-detected-from-rstudio/44035904#44035904

Running this code installed the matrixStats package using Rtools:

```
install.packages("remotes")
library(remotes)
Sys.setenv(PATH = paste("C:/Rtools/bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")
remotes::install_github("HenrikBengtsson/matrixStats@develop")
```
And it gets even better, the consistent R crashes I experienced for weeks when working with the STM package, or when running the test below are now gone :) 

library("matrixStats")
x <- matrix(runif(1e5*70), nrow=1e5)
y <- rowLogSumExps(x) # this causes the crash
