### ISSUE TITLE
Different arg names for input matrix

### ISSUE THREAD

**Issue by PeteHaitch** [HenrikBengtsson/matrixStats#122]
Almost certainly something you don't want to change now, but is there a reason `colAvgsPerRowSet()` and `rowAvgsPerColSet()` use `X`, and `colLogSumExps()` and `rowLogSumExps()` use `lx`, instead of `x` as their first arg?

**Comment by HenrikBengtsson** [comment]
It's intentional for the purpose of clarify that the input should be `log(x)` rather than `x` in order for the following (from `?logSumExp` to make sense / hold:

> Accurately computes the logarithm of the sum of exponentials, that is, log(sum(exp(lx))). If lx = log(x), then this is equivalently to calculating log(sum(x)). 

It would have been much more cumbersome to document if the argument was only `x`.  By using `lx` it's hopefully a bit more clear and the risk for mistakes being a bit lower.

Also, the R internals use a similar "strategy" - from WRE:

> * Function: double logspace_add (double logx, double logy)
> * Function: double logspace_sub (double logx, double logy)
> * Function: double logspace_sum (const double* logx, int n)
> 
>     Compute the log of a sum or difference from logs of terms, i.e., “x + y” as log (exp(logx) + exp(logy)) and “x - y” as log (exp(logx) - exp(logy)), and “sum_i x[i]” as log (sum[i = 1:n exp(logx[i])] ) without causing unnecessary overflows or throwing away too much accuracy.

**Comment by PeteHaitch** [comment]
I knew you'd have a good answer :) Thanks, Henrik!
