### ISSUE TITLE
Missing values and rowAvgsPerColSet()

### ISSUE THREAD

**Issue by const-ae** [HenrikBengtsson/matrixStats#169]
Hi,

I was just playing around with the `rowAvgsPerColSet()` function and noticed that its behavior with respect to the `na.rm` parameter is surprising:

``` r
library(matrixStats)
mat <- matrix(rnorm(20), nrow = 5, ncol = 4)
mat[2, 1] <- NA
print(mat)
#>            [,1]       [,2]       [,3]       [,4]
#> [1,] -1.4992304  1.3614587 -0.6052204  0.3892473
#> [2,]         NA  1.3000813 -0.4310598  0.6396945
#> [3,] -0.1071303  0.7881218 -0.9805042 -0.2417887
#> [4,]  0.6468310  0.8093626  0.2141994 -0.6034133
#> [5,] -0.8463808 -0.4850501  0.5805231  1.2289427

S <- matrix(1:ncol(mat), ncol = 2)
print(S)
#>      [,1] [,2]
#> [1,]    1    3
#> [2,]    2    4

cbind(rowMeans2(mat, cols = 1:2),
      rowMeans2(mat, cols = 3:4))
#>             [,1]       [,2]
#> [1,] -0.06888586 -0.1079866
#> [2,]          NA  0.1043173
#> [3,]  0.34049578 -0.6111464
#> [4,]  0.72809678 -0.1946070
#> [5,] -0.66571544  0.9047329
rowAvgsPerColSet(mat, S = S, FUN = rowMeans2)
#>             [,1]       [,2]
#> [1,] -0.06888586 -0.1079866
#> [2,]  1.30008131  0.1043173
#> [3,]  0.34049578 -0.6111464
#> [4,]  0.72809678 -0.1946070
#> [5,] -0.66571544  0.9047329
rowAvgsPerColSet(mat, S = S, FUN = rowMeans2, na.rm=TRUE)
#> Error in FUN(Zjj, ..., na.rm = na.rm): formal argument "na.rm" matched by multiple actual arguments
```

<sup>Created on 2020-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is this the intended behavior?

**Comment by HenrikBengtsson** [comment]
This is because thes functions automatically set and pass `na.rm` internally;

https://github.com/HenrikBengtsson/matrixStats/blob/a411e054678ea5cf45e53dd18af3d80b5b097f2e/R/rowAvgsPerColSet.R#L97-L98

So, it does not really make sense to specify `na.rm`.  But again, these functions are very much outliers in the matrixStats API (and probably only exists because we needed them in our microarray work back in 2005-2010).  

Maybe, it would help to add an `na.rm = TRUE` argument and then either:

```r
hasNA <- (anyMissing(X) || anyMissing(S))
na.rm <- na.rm && hasNA
```

or

```r
hasNA <- (anyMissing(X) || anyMissing(S))
na.rm <- na.rm || hasNA
```

internally.  The latter would be backward compatible and make the new `na.rm` argument more of a dummy in the sense that one can force `na.rm=TRUE` even if there are no missing data in the input, but one cannot force `na.rm = FALSE`.  I guess it's vice versa for the former version.   A third alternative is to use `na.rm = NA` by default which resolves to:

```r
if (is.na(na.rm)) na.rm <- (anyMissing(X) || anyMissing(S))
```

That would also be backward compatible and allow for full control of `na.rm = TRUE/FALSE`.

Thoughts?


BTW, `na.rm` is somewhat mentioned in the help:

https://github.com/HenrikBengtsson/matrixStats/blob/a411e054678ea5cf45e53dd18af3d80b5b097f2e/R/rowAvgsPerColSet.R#L25-L30

**Comment by HenrikBengtsson** [comment]
`colAvgsPerRowSet()` and `rowAvgsPerRowSet()` gained argument 'na.rm', where `na.rm = NA` is the default (for backward compatibility reasons), when we use `if (is.na(na.rm)) na.rm <- (anyMissing(X) || anyMissing(S))`.
