### ISSUE TITLE
colAnyMissings throws an error when passed a data frame

### ISSUE THREAD

**Issue by wmyashar23** [HenrikBengtsson/matrixStats#171]
Hi Henrik,

When I try calling the colAnyMissings function to a dataframe, it throws the error below:

Error: Argument 'x' is of class ‘data.frame’, but should be a matrix or a vector. The use of a ‘data.frame’ is not supported, the correctness of the result is not guaranteed. Please update your code accordingly.

The other functions have worked fine with the data frame that I've been using. I confirmed that I'm using the most recent package update.

Thanks!

**Comment by HenrikBengtsson** [comment]
That is by design.  These days there shouldn't be many functions that support data.frame:s as input.  The reason is that data.frame:s are such different creates, in what they can represent but also how the store data.  So, we're focusing on matrices (!= data.frame) and since some functions are basically also implemented internally for vectors we have some vector functions too.

You can read more about this on https://github.com/HenrikBengtsson/matrixStats/issues/18#issuecomment-206557747.
