### ISSUE TITLE
colCumprods() does not support logical input

### ISSUE THREAD

**Issue by const-ae** [HenrikBengtsson/matrixStats#178]
Hi Henrik,

unlike `colSums()`, `colProds()`, and  `colCumsums()` the `colCumprods()` cannot handle logical input: 

``` r
tmp <- matrix(rep(c(TRUE, TRUE, FALSE), 32), nrow = 8, ncol = 4)
tmp
#>       [,1]  [,2]  [,3]  [,4]
#> [1,]  TRUE FALSE  TRUE  TRUE
#> [2,]  TRUE  TRUE FALSE  TRUE
#> [3,] FALSE  TRUE  TRUE FALSE
#> [4,]  TRUE FALSE  TRUE  TRUE
#> [5,]  TRUE  TRUE FALSE  TRUE
#> [6,] FALSE  TRUE  TRUE FALSE
#> [7,]  TRUE FALSE  TRUE  TRUE
#> [8,]  TRUE  TRUE FALSE  TRUE
matrixStats::colSums2(tmp)
#> [1] 6 5 5 6
matrixStats::colProds(tmp)
#> [1] 0 0 0 0
matrixStats::colCumsums(tmp)
#>      [,1] [,2] [,3] [,4]
#> [1,]    1    0    1    1
#> [2,]    2    1    1    2
#> [3,]    2    2    2    2
#> [4,]    3    2    3    3
#> [5,]    4    3    3    4
#> [6,]    4    4    4    4
#> [7,]    5    4    5    5
#> [8,]    6    5    5    6
matrixStats::colCumprods(tmp)
#> Error in matrixStats::colCumprods(tmp): Argument 'x' cannot be logical.
```

<sup>Created on 2020-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is there a specific reason for this inconsistency?

Best, Constantin

PS: I realize that I have open a lot of issues lately for your repo with those very minor issues. I know that you are busy, so if you want me to report only the serious bugs to reduce the noise, just let me know :)

**Comment by HenrikBengtsson** [comment]
> Is there a specific reason for this inconsistency?

An oversight.  If you're up for it, I'd appreciate a PR.

Long story: The reason is that the others just (re-)gained support for logical input.  Several versions back the API took a _conservative_ approach to support only numeric input for several functions where it was not obvious other data types applied.  This was to peel away potential mistakes.  This was inspired by the API overhaul where support for data.frame:s was dropped.

Later it was argued that some of these functions make sense also for logical input.  Honestly, from a purist point of view, I'm still not certain I understand what the sum of a set of logical really means. OTH, since it's so commonly used to mean "the number TRUE elements" and all of us are used to do `sum(<logical>)`, `colSums()` was re-introduced (although, `count()` and `colCounts()` work).  It's also an implementation issue: several of these cases can be handled by the same native code that handles integers.

**Comment by const-ae** [comment]
I created PR https://github.com/HenrikBengtsson/matrixStats/pull/180

**Comment by HenrikBengtsson** [comment]
Thank you. This PR has also been merged.
