### ISSUE TITLE
CRAN: Fix before 2024-09-20

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#266]
```
From: Kurt Hornik <Kurt.Hornik@wu.ac.at>
Date: Mon, Aug 19, 2024 at 2:27 AM
Subject: CRAN package matrixStats
To: <henrikb@braju.com>
Cc: <CRAN@r-project.org>


Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_matrixStats.html>.

Specifically, please see the *Strict* additional issue.

Compilation fails with _R_USE_STRICT_R_HEADERS_=true, which defines
STRICT_R_HEADERS to 1 which removes

- the legacy definition of PI (use POSIX's M_PI, available in R fer ever).
- the RS.h declarations for Calloc, Realloc, Free (use R_ forms i
  available since R 3.4.0).

The aim is to clean the namespace: in particular having a definition
for Free has conflicted with some packages' C++ code.

It is planned that STRICT_R_HEADERS=1 will become the default for 4.5.0,
which in particular makes it necesssary that all CRAN packages with many
strong reverse dependencies compile/install ok with the new default.

Your package is among the ones with many strong reverse dependencies.
We would thus really appreciate if you could provide a new version of
your package as soon as possible which checks ok with
STRICT_R_HEADERS=1.

You can verify that your package checks ok with STRICT_R_HEADERS=1 via R
CMD check --as-cran using a current version of R-devel.

Please correct before 2024-09-20 to safely retain your package on CRAN.

Best,
-k
```

**Comment by yaccos** [comment]
This is one of the few cases where the R core team almost forces us to discard backwards compatibility. As far as I can see, the problem is caused by the `Calloc()` and their corresponding `Free()` calls present in `validateIndices_lowlevel_template.h`, `diff2_lowlevel_template.h`, and `rowDiffs_lowlevel_template.h`. These are to be replaced with `R_Calloc()` and `R_Free()` respectively. The problem is that these new functions names are only available in R 3.4.0 or later, whereas `matrixStats` is written to support all R versions from 2.12.0. In my view, leaves us with two options:

1. Lift the version requirment for the coming release from 2.12.0 to 3.4.0. Have there been any checks that `matrixStats` still works with these old versions?
2. Make use of macros such as `#ifdef _R_USE_STRICT_R_HEADERS_` to have code which is compiled differently on new and old R versions.

The first option is the cleanest one, but drops support for the mentioned old R versions, whereas the second options retains all backwards compatibility of the cost of a more complex codebase.

**Comment by HenrikBengtsson** [comment]
Would an alternative be to define R_Calloc() and R_Free(), if not already defined? If not, I guess we have to move to R (>= 3.4.0) released on April 2017.

**Comment by yaccos** [comment]
As far as I know, there is no direct way to make the preprocessor know which functions are declared as this is done after the preprocessor has finished. Hence, a conditional redefinition of a function in C is [impossible](https://stackoverflow.com/questions/1749233/check-whether-function-is-declared-with-c-preprocessor). What I could do however, is writing something like ([existing example](https://github.com/HenrikBengtsson/matrixStats/blob/2d1240f3f3ef08927a6a20b04853b26a154192c0/src/000.types.h#L30))

```C
#ifdef _R_USE_STRICT_R_HEADERS_
#define R_CALLOC(x) R_Calloc(x)
#else
#define R_CALLOC(x) Calloc(x)
#endif
```
and then changing the occurances of `Calloc()` to `R_CALLOC()`. However, this solution might bring problems in the future if `Calloc()` is removed entirely (leaving `R_CALLOC()` as the only remaining option). If so, the compilation will fail if `_R_USE_STRICT_R_HEADERS_` is not set. Are we willing to run this risk?

**Comment by HenrikBengtsson** [comment]
I see.

> Are we willing to run this risk?

Yes, let's do it. If this will only work for so long, we'll move to R (>= 3.4.0).

Thank you!
