### ISSUE TITLE
logSumExp: returns NaN for argument c(-Inf,-Inf,...,-Inf)

### ISSUE THREAD

**Issue by jasonxu90** [HenrikBengtsson/matrixStats#84]
Should hard-code logSumExp to return zero if max(argument)==-Inf

**Comment by HenrikBengtsson** [comment]
Thanks for this.  You wrote "zero" but you meant to say "to return -Inf", correct?

Because, a [few properties](https://en.wikipedia.org/wiki/LogSumExp) of `logSumExp(x)` that should hold:

1. "function is convex, and is strictly monotonically increasing everywhere in its domain"
2 Bounded as: max(x) <= logSumExp(x) <= max(x) + length(x)  (when there are no zeros in x)

Thus, if max(x) == -Inf then we should have -Inf <= logSumExp(x) <= -Inf + length(x), i.e. -Inf <= logSumExp(x) <= -Inf or simply logSumExp(x) = -Inf.

# Issue
The current implementation (matrixStats 0.50.1) gives
```r
> logSumExp(c(-Inf, -Inf))
[1] NaN
```
but should really give
```r
> logSumExp(c(-Inf, -Inf))
[1] -Inf
```

Note that this is only when there are strictly more than one `-Inf` value in `x`, e.g.
```r
> logSumExp(c(-Inf))
[1] -Inf
> logSumExp(c(-Inf, NA), na.rm=TRUE)
[1] -Inf
> logSumExp(c(-Inf, -Inf))
[1] NaN
> logSumExp(c(-Inf, -Inf, NA), na.rm=TRUE)
[1] NaN
> logSumExp(c(-Inf, -Inf, -Inf))
[1] NaN
[...]
```
The reason for the first case being correct is that it simply returns `x` in `logSumExp(x)` if `length(x) == 1` (and `x` is not missing), cf. https://github.com/HenrikBengtsson/matrixStats/blob/master/src/logSumExp_TYPE-template.h#L62-L68.

**Comment by jasonxu90** [comment]
Yes-- my function also exponentiates the whole term, and I have that return zero, so equivalently the logsumexp should just return -Inf.

Thanks!

**Comment by umanwizard** [comment]
The issue is here:

https://github.com/HenrikBengtsson/matrixStats/blob/master/src/logSumExp_TYPE-template.h#L168

since -Inf - -Inf is NaN.

**Comment by HenrikBengtsson** [comment]
Thanks for PR #85; would you mind adding tests to:

* https://github.com/HenrikBengtsson/matrixStats/blob/master/tests/logSumExp.R
* https://github.com/HenrikBengtsson/matrixStats/blob/master/tests/rowLogSumExps.R

as well?

BTW, the reason for the Travis CI tests [show errors](https://travis-ci.org/HenrikBengtsson/matrixStats/pull_requests) is that there is currently [a hiccup in the r-builder framework](https://github.com/metacran/r-builder/issues/46) that we're using.

**Comment by umanwizard** [comment]
Updated the PR.

**Comment by HenrikBengtsson** [comment]
Thanks :) I'll try to bring this in the next few days.

**Comment by HenrikBengtsson** [comment]
Thanks again; this fix will go into the next CRAN release (ETA currently unknown).  Until then, it can be installed as:
```r
source("http://callr.org/install#HenrikBengtsson/fix/logSumExp")
```

**Comment by HenrikBengtsson** [comment]
matrixStats 0.50.2 solving this issue just hit CRAN and should be rolling out across world soon:

  https://cran.r-project.org/web/packages/matrixStats/
