### ISSUE TITLE
colWeightedMeans throws error message when passed data frame with NA and using na.rm=T

### ISSUE THREAD

**Issue by pbaylis** [HenrikBengtsson/matrixStats#86]
I am using colWeightedMeans (matrixStats) to compute the weighted means of a set of columns. I noticed that it functions mostly normally if I pass it a data.frame, except that it throws an error (`new columns would leave holes after existing columns`) if passed a data.frame with NA values when na.rm=TRUE. If I transform the data.frame to a matrix, however, it works fine. MWE:

    df <- data.frame(c1=c(1,2), c2=c(2, NA))
    mtx <- as.matrix(df)
    colWeightedMeans(x=df,w=c(0.5, 0.5), na.rm=T) # Error
    colWeightedMeans(x=mtx,w=c(0.5, 0.5), na.rm=T) # Works

Is this the desired behavior? The error message wasn't intuitive to me.

**Comment by HenrikBengtsson** [comment]
Thanks for the report.  First, in case someone else see this, the error occurs with:
```r
> library(matrixStats)
matrixStats v0.50.2 (2016-04-24) successfully loaded. See ?matrixStats for help.
> df <- data.frame(c1=c(1,2), c2=c(2, NA))
> colWeightedMeans(x=df,w=c(0.5, 0.5), na.rm=TRUE)
Error in `[<-.data.frame`(`*tmp*`, nas, value = 0) :
  new columns would leave holes after existing columns
```
and just for the record with `na.rm=FALSE`, we get:
```r
> colWeightedMeans(x=df, w=c(0.5, 0.5), na.rm=FALSE)
 c1  c2
1.5  NA
```

Now, to the important point, the matrixStats package is **only for matrices** and not for data frames (which are completely different creatures(*) in R despite they both have rows and column).  See Issue #18 for a discussion on and explanation for why matrixStats does not support data frames - it's an intentional decision.

Having said this, it's indeed a bit confusing that `colWeightedMeans()` works with data frames in some cases.  Technically this is because in certain cases it falls back to using `base::colSums()` and `base::colMeans()` and those do indeed support data frames.  Maybe it would be better if matrixStats tests for non-matrix objects everywhere and give an informative error message rather than (silently work/somewhat work).  I've created a separate issue for this - see Issue #87.

(*) For example, matrices contains values of a single data type, whereas for data frames each column may have a specific data type.  Also, when you transpose a matrix it's still a matrix and `X == t(t(X))` is true for matrices but not data frames.
